# Generated by Django 3.0.4 on 2020-05-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='Id_Achats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Achats.Achats'),
        ),
        migrations.AlterField(
            model_name='association',
            name='Id_Article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Achats.Article'),
        ),
    ]
