# Generated by Django 3.0.4 on 2020-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats',
            name='Montant_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
