# Generated by Django 3.0.4 on 2020-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0002_achats_montant_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('E_S', models.BooleanField()),
                ('mode_de_payement', models.IntegerField()),
                ('reference', models.IntegerField()),
                ('Montant_HT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Numero_facture', models.IntegerField()),
                ('Numero_payement', models.IntegerField()),
            ],
        ),
    ]
