# Generated by Django 3.0.4 on 2020-04-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0002_achats_assocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assocation',
            new_name='Association',
        ),
    ]
