# Generated by Django 3.0.4 on 2020-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0003_auto_20200419_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achats',
            name='Date',
            field=models.DateField(),
        ),
    ]
