# Generated by Django 3.0.4 on 2020-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0004_auto_20200419_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='Prix_Unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='association',
            name='Quantite',
            field=models.IntegerField(default=1),
        ),
    ]
