# Generated by Django 3.0.4 on 2020-05-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Achats', '0006_auto_20200502_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payements',
            name='E_S',
            field=models.CharField(max_length=10),
        ),
    ]
