# Generated by Django 3.0.4 on 2020-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fournis_Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournis_contact',
            name='contact_type',
            field=models.CharField(default='Fournis_contact', max_length=50),
        ),
    ]
