# Generated by Django 3.0.8 on 2020-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fournis_Section', '0003_auto_20200729_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournis_data',
            name='Banque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fournis_data',
            name='CB',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fournis_data',
            name='RC',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fournis_data',
            name='Raison_social',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
