# Generated by Django 3.0.4 on 2020-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ES', models.CharField(choices=[('Chéque', 'Chéque'), ('Espéces', 'Espéces'), ('Virement', 'Virement')], max_length=200)),
                ('Date', models.DateField()),
                ('Nature', models.TextField()),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
