# Generated by Django 3.0.4 on 2020-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caisse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='ES',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Charge', 'Charge'), ('Dépence', 'Dépence')], max_length=200),
        ),
    ]
