# Generated by Django 3.0.4 on 2020-06-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caisse', '0002_auto_20200528_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='ES',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Charge', 'Charge'), ('Dépence', 'Dépence'), ('Alimentation', 'Alimentation')], max_length=200),
        ),
    ]
