# Generated by Django 3.0.4 on 2020-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='Debut_realsiation',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
