# Generated by Django 3.0.4 on 2020-05-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0002_modalite_debut_realsiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='Garantie',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
