# Generated by Django 3.0.4 on 2020-05-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0005_auto_20200507_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Date_validation',
        ),
    ]
