# Generated by Django 3.0.4 on 2020-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0006_remove_commande_date_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Date_validation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
