# Generated by Django 3.0.4 on 2020-05-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0007_commande_date_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Etat', models.BooleanField(default=False)),
                ('Titre_facture', models.CharField(max_length=200)),
                ('Numero_facture', models.CharField(max_length=200)),
                ('Montant_HT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proformas.Commande')),
            ],
        ),
    ]
