# Generated by Django 3.0.4 on 2020-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0008_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Date_limite_payement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='Date_payement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
