# Generated by Django 3.0.4 on 2020-05-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0009_auto_20200509_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proformas.Commande', unique=True),
        ),
    ]
