# Generated by Django 3.0.4 on 2020-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0010_auto_20200517_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Numero_facture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
