# Generated by Django 3.0.4 on 2020-06-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0011_auto_20200619_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='validation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
