# Generated by Django 3.0.4 on 2020-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0013_auto_20200619_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalite',
            name='Debut_realsiation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
