# Generated by Django 3.0.8 on 2020-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0015_auto_20200803_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_designation',
            name='Montant_HT',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commande_designation',
            name='Montant_TTC',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commande_designation',
            name='Montant_TVA',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
