# Generated by Django 3.0.8 on 2020-08-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proformas', '0019_auto_20200803_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_designation',
            name='Command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Proformas.Commande'),
        ),
    ]
