# Generated by Django 3.0.4 on 2020-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_Section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_data',
            old_name='Name',
            new_name='CB',
        ),
        migrations.RemoveField(
            model_name='client_data',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='client_data',
            name='tel',
        ),
        migrations.AddField(
            model_name='client_data',
            name='AI',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='Banque',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='NIF',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='NIS',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='Raison_social',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
