# Generated by Django 3.0.4 on 2020-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_Section', '0002_auto_20200402_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='AI',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='Banque',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='NIF',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='NIS',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='Raison_social',
            field=models.CharField(max_length=254),
        ),
    ]
