# Generated by Django 3.0.4 on 2020-04-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_Section', '0005_auto_20200402_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Client_Section.Client_Data'),
        ),
    ]
