# Generated by Django 3.0.4 on 2020-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Date_limit', models.DateField()),
                ('Etat', models.BooleanField(default=False)),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField()),
                ('Designation_charge', models.CharField(choices=[('Casnos', 'Casnos'), ('Cnas', 'Cnas'), ('Salaire', 'Salaire'), ('G50', 'G50'), ('Bilan', 'Bilan'), ('Notaire', 'Notaire'), ('Charge diver', 'Charge Diver')], max_length=200)),
            ],
        ),
    ]
