# Generated by Django 3.0.4 on 2020-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactionb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionb',
            name='Date_transaction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionb',
            name='validation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
