# Generated by Django 3.0.4 on 2020-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactionb', '0002_auto_20200515_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionb',
            name='Numero_facture',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transactionb',
            name='reference',
            field=models.IntegerField(blank=True),
        ),
    ]
